name: os_sports_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.4
  json_serializable: ^6.3.0
  lints: ^2.0.0
  retrofit_generator: ^4.0.1

dependencies:
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.6.0
  retrofit: ^3.0.1+1

dependency_overrides:
  analyzer: ^4.2.0
