name: os_sports_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.3 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  lints: ^2.0.0
  retrofit_generator: ^4.0.1

dependencies:
  collection: ^1.16.0
  compute: ^1.0.0
  deep_pick: ^0.10.0
  dio: ^4.0.6
  http: ^0.13.4
  json_annotation: ^4.5.0
  recase: ^4.0.0
  retrofit: ^3.0.1+1
