// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'team_overall_statistics.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TeamOverallStatistics _$TeamOverallStatisticsFromJson(
        Map<String, dynamic> json) =>
    TeamOverallStatistics(
      goalsScored: json['goalsScored'] as int?,
      goalsConceded: json['goalsConceded'] as int?,
      ownGoals: json['ownGoals'] as int?,
      assists: json['assists'] as int?,
      shots: json['shots'] as int?,
      penaltyGoals: json['penaltyGoals'] as int?,
      penaltiesTaken: json['penaltiesTaken'] as int?,
      freeKickGoals: json['freeKickGoals'] as int?,
      freeKickShots: json['freeKickShots'] as int?,
      goalsFromInsideTheBox: json['goalsFromInsideTheBox'] as int?,
      goalsFromOutsideTheBox: json['goalsFromOutsideTheBox'] as int?,
      shotsFromInsideTheBox: json['shotsFromInsideTheBox'] as int?,
      shotsFromOutsideTheBox: json['shotsFromOutsideTheBox'] as int?,
      headedGoals: json['headedGoals'] as int?,
      leftFootGoals: json['leftFootGoals'] as int?,
      rightFootGoals: json['rightFootGoals'] as int?,
      bigChances: json['bigChances'] as int?,
      bigChancesCreated: json['bigChancesCreated'] as int?,
      bigChancesMissed: json['bigChancesMissed'] as int?,
      shotsOnTarget: json['shotsOnTarget'] as int?,
      shotsOffTarget: json['shotsOffTarget'] as int?,
      blockedScoringAttempt: json['blockedScoringAttempt'] as int?,
      successfulDribbles: json['successfulDribbles'] as int?,
      dribbleAttempts: json['dribbleAttempts'] as int?,
      corners: json['corners'] as int?,
      hitWoodwork: json['hitWoodwork'] as int?,
      fastBreaks: json['fastBreaks'] as int?,
      fastBreakGoals: json['fastBreakGoals'] as int?,
      fastBreakShots: json['fastBreakShots'] as int?,
      averageBallPossession:
          (json['averageBallPossession'] as num?)?.toDouble(),
      totalPasses: json['totalPasses'] as int?,
      accuratePasses: json['accuratePasses'] as int?,
      accuratePassesPercentage:
          (json['accuratePassesPercentage'] as num?)?.toDouble(),
      totalOwnHalfPasses: json['totalOwnHalfPasses'] as int?,
      accurateOwnHalfPasses: json['accurateOwnHalfPasses'] as int?,
      accurateOwnHalfPassesPercentage:
          (json['accurateOwnHalfPassesPercentage'] as num?)?.toDouble(),
      totalOppositionHalfPasses: json['totalOppositionHalfPasses'] as int?,
      accurateOppositionHalfPasses:
          json['accurateOppositionHalfPasses'] as int?,
      accurateOppositionHalfPassesPercentage:
          (json['accurateOppositionHalfPassesPercentage'] as num?)?.toDouble(),
      totalLongBalls: json['totalLongBalls'] as int?,
      accurateLongBalls: json['accurateLongBalls'] as int?,
      accurateLongBallsPercentage:
          (json['accurateLongBallsPercentage'] as num?)?.toDouble(),
      totalCrosses: json['totalCrosses'] as int?,
      accurateCrosses: json['accurateCrosses'] as int?,
      accurateCrossesPercentage:
          (json['accurateCrossesPercentage'] as num?)?.toDouble(),
      cleanSheets: json['cleanSheets'] as int?,
      tackles: json['tackles'] as int?,
      interceptions: json['interceptions'] as int?,
      saves: json['saves'] as int?,
      errorsLeadingToGoal: json['errorsLeadingToGoal'] as int?,
      errorsLeadingToShot: json['errorsLeadingToShot'] as int?,
      penaltiesCommited: json['penaltiesCommited'] as int?,
      penaltyGoalsConceded: json['penaltyGoalsConceded'] as int?,
      clearances: json['clearances'] as int?,
      clearancesOffLine: json['clearancesOffLine'] as int?,
      lastManTackles: json['lastManTackles'] as int?,
      totalDuels: json['totalDuels'] as int?,
      duelsWon: json['duelsWon'] as int?,
      duelsWonPercentage: (json['duelsWonPercentage'] as num?)?.toDouble(),
      totalGroundDuels: json['totalGroundDuels'] as int?,
      groundDuelsWon: json['groundDuelsWon'] as int?,
      groundDuelsWonPercentage:
          (json['groundDuelsWonPercentage'] as num?)?.toDouble(),
      totalAerialDuels: json['totalAerialDuels'] as int?,
      aerialDuelsWon: json['aerialDuelsWon'] as int?,
      aerialDuelsWonPercentage:
          (json['aerialDuelsWonPercentage'] as num?)?.toDouble(),
      possessionLost: json['possessionLost'] as int?,
      offsides: json['offsides'] as int?,
      fouls: json['fouls'] as int?,
      yellowCards: json['yellowCards'] as int?,
      yellowRedCards: json['yellowRedCards'] as int?,
      redCards: json['redCards'] as int?,
      avgRating: (json['avgRating'] as num?)?.toDouble(),
      accurateFinalThirdPassesAgainst:
          json['accurateFinalThirdPassesAgainst'] as int?,
      accurateOppositionHalfPassesAgainst:
          json['accurateOppositionHalfPassesAgainst'] as int?,
      accurateOwnHalfPassesAgainst:
          json['accurateOwnHalfPassesAgainst'] as int?,
      accuratePassesAgainst: json['accuratePassesAgainst'] as int?,
      bigChancesAgainst: json['bigChancesAgainst'] as int?,
      bigChancesCreatedAgainst: json['bigChancesCreatedAgainst'] as int?,
      bigChancesMissedAgainst: json['bigChancesMissedAgainst'] as int?,
      clearancesAgainst: json['clearancesAgainst'] as int?,
      cornersAgainst: json['cornersAgainst'] as int?,
      crossesSuccessfulAgainst: json['crossesSuccessfulAgainst'] as int?,
      crossesTotalAgainst: json['crossesTotalAgainst'] as int?,
      dribbleAttemptsTotalAgainst: json['dribbleAttemptsTotalAgainst'] as int?,
      dribbleAttemptsWonAgainst: json['dribbleAttemptsWonAgainst'] as int?,
      errorsLeadingToGoalAgainst: json['errorsLeadingToGoalAgainst'] as int?,
      errorsLeadingToShotAgainst: json['errorsLeadingToShotAgainst'] as int?,
      hitWoodworkAgainst: json['hitWoodworkAgainst'] as int?,
      interceptionsAgainst: json['interceptionsAgainst'] as int?,
      keyPassesAgainst: json['keyPassesAgainst'] as int?,
      longBallsSuccessfulAgainst: json['longBallsSuccessfulAgainst'] as int?,
      longBallsTotalAgainst: json['longBallsTotalAgainst'] as int?,
      offsidesAgainst: json['offsidesAgainst'] as int?,
      redCardsAgainst: json['redCardsAgainst'] as int?,
      shotsAgainst: json['shotsAgainst'] as int?,
      shotsBlockedAgainst: json['shotsBlockedAgainst'] as int?,
      shotsFromInsideTheBoxAgainst:
          json['shotsFromInsideTheBoxAgainst'] as int?,
      shotsFromOutsideTheBoxAgainst:
          json['shotsFromOutsideTheBoxAgainst'] as int?,
      shotsOffTargetAgainst: json['shotsOffTargetAgainst'] as int?,
      shotsOnTargetAgainst: json['shotsOnTargetAgainst'] as int?,
      blockedScoringAttemptAgainst:
          json['blockedScoringAttemptAgainst'] as int?,
      tacklesAgainst: json['tacklesAgainst'] as int?,
      totalFinalThirdPassesAgainst:
          json['totalFinalThirdPassesAgainst'] as int?,
      oppositionHalfPassesTotalAgainst:
          json['oppositionHalfPassesTotalAgainst'] as int?,
      ownHalfPassesTotalAgainst: json['ownHalfPassesTotalAgainst'] as int?,
      totalPassesAgainst: json['totalPassesAgainst'] as int?,
      yellowCardsAgainst: json['yellowCardsAgainst'] as int?,
      id: json['id'] as int?,
      matches: json['matches'] as int?,
      awardedMatches: json['awardedMatches'] as int?,
    );

Map<String, dynamic> _$TeamOverallStatisticsToJson(
        TeamOverallStatistics instance) =>
    <String, dynamic>{
      'goalsScored': instance.goalsScored,
      'goalsConceded': instance.goalsConceded,
      'ownGoals': instance.ownGoals,
      'assists': instance.assists,
      'shots': instance.shots,
      'penaltyGoals': instance.penaltyGoals,
      'penaltiesTaken': instance.penaltiesTaken,
      'freeKickGoals': instance.freeKickGoals,
      'freeKickShots': instance.freeKickShots,
      'goalsFromInsideTheBox': instance.goalsFromInsideTheBox,
      'goalsFromOutsideTheBox': instance.goalsFromOutsideTheBox,
      'shotsFromInsideTheBox': instance.shotsFromInsideTheBox,
      'shotsFromOutsideTheBox': instance.shotsFromOutsideTheBox,
      'headedGoals': instance.headedGoals,
      'leftFootGoals': instance.leftFootGoals,
      'rightFootGoals': instance.rightFootGoals,
      'bigChances': instance.bigChances,
      'bigChancesCreated': instance.bigChancesCreated,
      'bigChancesMissed': instance.bigChancesMissed,
      'shotsOnTarget': instance.shotsOnTarget,
      'shotsOffTarget': instance.shotsOffTarget,
      'blockedScoringAttempt': instance.blockedScoringAttempt,
      'successfulDribbles': instance.successfulDribbles,
      'dribbleAttempts': instance.dribbleAttempts,
      'corners': instance.corners,
      'hitWoodwork': instance.hitWoodwork,
      'fastBreaks': instance.fastBreaks,
      'fastBreakGoals': instance.fastBreakGoals,
      'fastBreakShots': instance.fastBreakShots,
      'averageBallPossession': instance.averageBallPossession,
      'totalPasses': instance.totalPasses,
      'accuratePasses': instance.accuratePasses,
      'accuratePassesPercentage': instance.accuratePassesPercentage,
      'totalOwnHalfPasses': instance.totalOwnHalfPasses,
      'accurateOwnHalfPasses': instance.accurateOwnHalfPasses,
      'accurateOwnHalfPassesPercentage':
          instance.accurateOwnHalfPassesPercentage,
      'totalOppositionHalfPasses': instance.totalOppositionHalfPasses,
      'accurateOppositionHalfPasses': instance.accurateOppositionHalfPasses,
      'accurateOppositionHalfPassesPercentage':
          instance.accurateOppositionHalfPassesPercentage,
      'totalLongBalls': instance.totalLongBalls,
      'accurateLongBalls': instance.accurateLongBalls,
      'accurateLongBallsPercentage': instance.accurateLongBallsPercentage,
      'totalCrosses': instance.totalCrosses,
      'accurateCrosses': instance.accurateCrosses,
      'accurateCrossesPercentage': instance.accurateCrossesPercentage,
      'cleanSheets': instance.cleanSheets,
      'tackles': instance.tackles,
      'interceptions': instance.interceptions,
      'saves': instance.saves,
      'errorsLeadingToGoal': instance.errorsLeadingToGoal,
      'errorsLeadingToShot': instance.errorsLeadingToShot,
      'penaltiesCommited': instance.penaltiesCommited,
      'penaltyGoalsConceded': instance.penaltyGoalsConceded,
      'clearances': instance.clearances,
      'clearancesOffLine': instance.clearancesOffLine,
      'lastManTackles': instance.lastManTackles,
      'totalDuels': instance.totalDuels,
      'duelsWon': instance.duelsWon,
      'duelsWonPercentage': instance.duelsWonPercentage,
      'totalGroundDuels': instance.totalGroundDuels,
      'groundDuelsWon': instance.groundDuelsWon,
      'groundDuelsWonPercentage': instance.groundDuelsWonPercentage,
      'totalAerialDuels': instance.totalAerialDuels,
      'aerialDuelsWon': instance.aerialDuelsWon,
      'aerialDuelsWonPercentage': instance.aerialDuelsWonPercentage,
      'possessionLost': instance.possessionLost,
      'offsides': instance.offsides,
      'fouls': instance.fouls,
      'yellowCards': instance.yellowCards,
      'yellowRedCards': instance.yellowRedCards,
      'redCards': instance.redCards,
      'avgRating': instance.avgRating,
      'accurateFinalThirdPassesAgainst':
          instance.accurateFinalThirdPassesAgainst,
      'accurateOppositionHalfPassesAgainst':
          instance.accurateOppositionHalfPassesAgainst,
      'accurateOwnHalfPassesAgainst': instance.accurateOwnHalfPassesAgainst,
      'accuratePassesAgainst': instance.accuratePassesAgainst,
      'bigChancesAgainst': instance.bigChancesAgainst,
      'bigChancesCreatedAgainst': instance.bigChancesCreatedAgainst,
      'bigChancesMissedAgainst': instance.bigChancesMissedAgainst,
      'clearancesAgainst': instance.clearancesAgainst,
      'cornersAgainst': instance.cornersAgainst,
      'crossesSuccessfulAgainst': instance.crossesSuccessfulAgainst,
      'crossesTotalAgainst': instance.crossesTotalAgainst,
      'dribbleAttemptsTotalAgainst': instance.dribbleAttemptsTotalAgainst,
      'dribbleAttemptsWonAgainst': instance.dribbleAttemptsWonAgainst,
      'errorsLeadingToGoalAgainst': instance.errorsLeadingToGoalAgainst,
      'errorsLeadingToShotAgainst': instance.errorsLeadingToShotAgainst,
      'hitWoodworkAgainst': instance.hitWoodworkAgainst,
      'interceptionsAgainst': instance.interceptionsAgainst,
      'keyPassesAgainst': instance.keyPassesAgainst,
      'longBallsSuccessfulAgainst': instance.longBallsSuccessfulAgainst,
      'longBallsTotalAgainst': instance.longBallsTotalAgainst,
      'offsidesAgainst': instance.offsidesAgainst,
      'redCardsAgainst': instance.redCardsAgainst,
      'shotsAgainst': instance.shotsAgainst,
      'shotsBlockedAgainst': instance.shotsBlockedAgainst,
      'shotsFromInsideTheBoxAgainst': instance.shotsFromInsideTheBoxAgainst,
      'shotsFromOutsideTheBoxAgainst': instance.shotsFromOutsideTheBoxAgainst,
      'shotsOffTargetAgainst': instance.shotsOffTargetAgainst,
      'shotsOnTargetAgainst': instance.shotsOnTargetAgainst,
      'blockedScoringAttemptAgainst': instance.blockedScoringAttemptAgainst,
      'tacklesAgainst': instance.tacklesAgainst,
      'totalFinalThirdPassesAgainst': instance.totalFinalThirdPassesAgainst,
      'oppositionHalfPassesTotalAgainst':
          instance.oppositionHalfPassesTotalAgainst,
      'ownHalfPassesTotalAgainst': instance.ownHalfPassesTotalAgainst,
      'totalPassesAgainst': instance.totalPassesAgainst,
      'yellowCardsAgainst': instance.yellowCardsAgainst,
      'id': instance.id,
      'matches': instance.matches,
      'awardedMatches': instance.awardedMatches,
    };
